name: Sync Image

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets
        shell: bash
        run: |
          echo "ACR_USERNAME=${ACR_USERNAME}"
          echo "ACR_PASSWORD length=${#ACR_PASSWORD}"

          if [ -z "$ACR_USERNAME" ]; then
            echo "ACR_USERNAME is empty"
            exit 1
          fi

          if [ -z "$ACR_PASSWORD" ]; then
            echo "ACR_PASSWORD is empty"
            exit 1
          fi

          echo "ACR_PASSWORD masked preview=${ACR_PASSWORD:0:2}****${ACR_PASSWORD: -2}"
        env:
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

      - name: Login to Aliyun ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            --username="${{ secrets.ACR_USERNAME }}" \
            --password-stdin \
            registry.cn-hangzhou.aliyuncs.com

      - name: Pull source image1
        run: |
          docker pull --platform linux/amd64 prom/prometheus:latest

      - name: Pull source image2
        run: |
          docker pull --platform linux/amd64 grafana/grafana:latest

      - name: Tag image1
        run: |
          docker tag prom/prometheus:latest registry.cn-hangzhou.aliyuncs.com/zgz521/prometheus:latest

      - name: Tag image
        run: |
          docker tag grafana/grafana:latest registry.cn-hangzhou.aliyuncs.com/zgz521/grafana:latest

      - name: Push image1 to Aliyun ACR
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/zgz521/prometheus:latest
          
      - name: Push image1 to Aliyun ACR
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/zgz521/grafana:latest
